#!/usr/bin/env bash
# Display information about subdomains.
display_subdomain_info() {
  local domain="$1"
  local subdomain="$2"

  # Default subdomains
  local default_subdomains=("www" "lb-01" "web-01" "web-02")

  # If specific subdomain is provided, use it; otherwise, use the default subdomains
  if [[ -n "$subdomain" ]]; then
    local subdomains=("$subdomain")
  else
    local subdomains=("${default_subdomains[@]}")
  fi

  # Loop through subdomains and display information
  for sub in "${subdomains[@]}"; do
    record_type=$(dig +nocmd "${sub}.${domain}" +noall +answer | awk '{print $4}')
    destination=$(dig +nocmd "${sub}.${domain}" +noall +answer | awk '{print $5}')
    echo "The subdomain ${sub}.${domain} is a ${record_type} record and points to ${destination}"
  done
}

  # Check if both domain and subdomain are provided as arguments
  if [[ $# -eq 2 ]]; then
    domain="$1"
    subdomain="$2"
    display_subdomain_info "$domain" "$subdomain"
  else
    echo "Error: Please provide both the domain and subdomain parameters."
  fi
