#!/usr/bin/env bash
# configures Nginx server so that /redirect_me is redirecting to another page
# The redirection must be a “301 Moved Permanently”
sudo apt-get -y update
sudo apt-get -y install nginx
sudo ufw allow 'Nginx HTTP'
echo "Hello World!" > sudo /var/www/html/index.html
sed -i "37i\rewrite ^/redirect_me https://www.youtube.com/watch?v=siwpn14IE7E&ab_channel=KennyLogginsVEVO permanent;" /etc/nginx/sites-available/default
sudo service nginx start
