#!/usr/bin/env bash
# configures server for nginx to be listening to port 80
rm /etc/nginx/sites-enabled/default
sudo -s /etc/nginx/sites-enabled/default /etc/nginx/sites-enabled/default
sudo service nginx restart
