#!/usr/bin/env bash

# Check if an argument is provided
if [[ $# -eq 0 ]]; then
  echo "Please provide a user as an argument"
  exit 1
fi

# Run whoami command under the user passed as an argument
sudo -u "$1" whoami
